// Dummy notifications data
const dummyNotifications = [
  {
    id: 1,
    title: "New booking from Sarah",
    description:
      "Sarah Johnson booked your 'Mountain Hiking Adventure' for October 15th",
    type: "booking",
    icon: "checkmark-circle",
    icon_color: "#10B981",
    time: "2 minutes ago",
    is_read: false,
  },
  {
    id: 2,
    title: "Schedule change request",
    description:
      "Mike Chen wants to reschedule 'City Food Tour' from Oct 12 to Oct 14",
    type: "schedule",
    icon: "time-outline",
    icon_color: "#F59E0B",
    time: "1 hour ago",
    is_read: false,
  },
  {
    id: 3,
    title: "Experience approved",
    description:
      "Your 'Sunset Photography Workshop' has been approved by admin",
    type: "approval",
    icon: "checkmark-circle",
    icon_color: "#10B981",
    time: "3 hours ago",
    is_read: true,
  },
  {
    id: 4,
    title: "New 5-star rating",
    description: "Emma left you a 5-star review for 'Cooking Class Experience'",
    type: "rating",
    icon: "star-outline",
    icon_color: "#F59E0B",
    time: "1 day ago",
    is_read: false,
  },
  {
    id: 5,
    title: "Message from traveler",
    description: "Alex has sent you a message about the upcoming trip",
    type: "message",
    icon: "location",
    icon_color: "#4F46E5",
    time: "2 days ago",
    is_read: true,
  },
  {
    id: 6,
    title: "Experience denied",
    description: "Your 'Rock Climbing Adventure' needs more safety information",
    type: "denial",
    icon: "close-circle-outline",
    icon_color: "#EF4444",
    time: "3 days ago",
    is_read: true,
  },
  {
    id: 7,
    title: "Experience denied",
    description: "Your 'Rock Climbing Adventure' needs more safety information",
    type: "denial",
    icon: "close-circle-outline",
    icon_color: "#EF4444",
    time: "3 days ago",
    is_read: true,
  },
  {
    id: 8,
    title: "Experience denied",
    description: "Your 'Rock Climbing Adventure' needs more safety information",
    type: "denial",
    icon: "close-circle-outline",
    icon_color: "#EF4444",
    time: "3 days ago",
    is_read: true,
  },
];
export default dummyNotifications;
